---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - spire.hpe.com
  resources:
  - spireservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spire.hpe.com
  resources:
  - spireservers/finalizers
  verbs:
  - update
- apiGroups:
  - spire.hpe.com
  resources:
  - spireservers/status
  verbs:
  - get
  - patch
  - update
