# permissions for end users to edit spireagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: spireagent-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spire-k8s-operator
    app.kubernetes.io/part-of: spire-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: spireagent-editor-role
rules:
- apiGroups:
  - spire.hpe.com
  resources:
  - spireagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spire.hpe.com
  resources:
  - spireagents/status
  verbs:
  - get
