# permissions for end users to edit spire-servers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: spire-server-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spire-k8s-operator
    app.kubernetes.io/part-of: spire-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: spire-server-editor-role
rules:
- apiGroups:
  - spire.hpe.com
  resources:
  - spire-servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spire.hpe.com
  resources:
  - spire-servers/status
  verbs:
  - get
