# permissions for end users to view spireservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: spireserver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spire-k8s-operator
    app.kubernetes.io/part-of: spire-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: spireserver-viewer-role
rules:
- apiGroups:
  - spire.hpe.com
  resources:
  - spireservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spire.hpe.com
  resources:
  - spireservers/status
  verbs:
  - get
