apiVersion: spire.hpe.com/v1
kind: SpireServer
metadata:
  name: invalid-spire-server
spec:
  trustDomain: example.org
  port: 8081
  nodeAttestors: 
    - name: k8s_sat
    - name: aws_iid
  keyStorage: disk
  replicas: 0
  dataStore: sqlite3
  connectionString: /run/spire/data/datastore.sqlite3