apiVersion: spire.hpe.com/v1
kind: SpireAgent
metadata:
  name: spire-agent-01
spec:
  trustDomain: example.org
  nodeAttestor: 
    name: k8s_sat
  workloadAttestors: 
    - name: k8s
    - name: unix
  keyStorage: memory
  serverPort: 8081